# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.tableWidget_bitmap = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_bitmap.setObjectName("tableWidget_bitmap")
        self.tableWidget_bitmap.setColumnCount(0)
        self.tableWidget_bitmap.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget_bitmap, 1, 1, 1, 1)
        self.tableWidget_files = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_files.setObjectName("tableWidget_files")
        self.tableWidget_files.setColumnCount(0)
        self.tableWidget_files.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget_files, 1, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 3)
        self.gridLayout_3.setColumnStretch(1, 5)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_randomset = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_randomset.setObjectName("checkBox_randomset")
        self.gridLayout.addWidget(self.checkBox_randomset, 1, 0, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_op = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_op.setObjectName("comboBox_op")
        self.comboBox_op.addItem("")
        self.comboBox_op.addItem("")
        self.comboBox_op.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_op, 1, 0, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout_2.addWidget(self.pushButton_run, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文件管理"))
        self.label.setText(_translate("MainWindow", "文件列表"))
        self.label_2.setText(_translate("MainWindow", "位示图"))
        self.groupBox.setTitle(_translate("MainWindow", "初始化与重置"))
        self.checkBox_randomset.setText(_translate("MainWindow", "随机初始化磁盘"))
        self.pushButton_reset.setText(_translate("MainWindow", "重置磁盘"))
        self.groupBox_2.setTitle(_translate("MainWindow", "操作"))
        self.comboBox_op.setItemText(0, _translate("MainWindow", "1. 随机生成50个文件"))
        self.comboBox_op.setItemText(1, _translate("MainWindow", "2. 删除奇数个文件"))
        self.comboBox_op.setItemText(2, _translate("MainWindow", "3. 再新建5个文件"))
        self.pushButton_run.setText(_translate("MainWindow", "执行"))
