# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView_fifo = QtWidgets.QTableView(self.groupBox)
        self.tableView_fifo.setObjectName("tableView_fifo")
        self.horizontalLayout.addWidget(self.tableView_fifo)
        self.textEdit_fifo = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_fifo.setObjectName("textEdit_fifo")
        self.horizontalLayout.addWidget(self.textEdit_fifo)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView_lru = QtWidgets.QTableView(self.groupBox_2)
        self.tableView_lru.setObjectName("tableView_lru")
        self.horizontalLayout_2.addWidget(self.tableView_lru)
        self.textEdit_lru = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_lru.setObjectName("textEdit_lru")
        self.horizontalLayout_2.addWidget(self.textEdit_lru)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_page_seq = QtWidgets.QLabel(self.groupBox_3)
        self.label_page_seq.setObjectName("label_page_seq")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_page_seq)
        self.lineEdit_page_seq = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_page_seq.setObjectName("lineEdit_page_seq")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_page_seq)
        self.label_size = QtWidgets.QLabel(self.groupBox_3)
        self.label_size.setObjectName("label_size")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_size)
        self.lineEdit_size = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_size.setObjectName("lineEdit_size")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_size)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_replace = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.horizontalLayout_4.addWidget(self.pushButton_replace)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "存储管理"))
        self.groupBox.setTitle(_translate("MainWindow", "FIFO替换算法"))
        self.groupBox_2.setTitle(_translate("MainWindow", "LRU替换算法"))
        self.groupBox_3.setTitle(_translate("MainWindow", "输入"))
        self.label_page_seq.setText(_translate("MainWindow", "页面序列"))
        self.label_size.setText(_translate("MainWindow", "页面框数"))
        self.pushButton_replace.setText(_translate("MainWindow", "替换"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
