# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_plot = QtWidgets.QWidget(self.centralwidget)
        self.widget_plot.setObjectName("widget_plot")
        self.verticalLayout.addWidget(self.widget_plot)
        self.tableWidget_process = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_process.setObjectName("tableWidget_process")
        self.tableWidget_process.setColumnCount(0)
        self.tableWidget_process.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_process)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_schedule = QtWidgets.QPushButton(self.frame)
        self.pushButton_schedule.setObjectName("pushButton_schedule")
        self.gridLayout.addWidget(self.pushButton_schedule, 5, 3, 1, 1)
        self.pushButton_random = QtWidgets.QPushButton(self.frame)
        self.pushButton_random.setObjectName("pushButton_random")
        self.gridLayout.addWidget(self.pushButton_random, 1, 3, 1, 1)
        self.comboBox_method = QtWidgets.QComboBox(self.frame)
        self.comboBox_method.setDuplicatesEnabled(False)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.gridLayout.addWidget(self.comboBox_method, 5, 1, 1, 1)
        self.frame_time_slice = QtWidgets.QFrame(self.frame)
        self.frame_time_slice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_time_slice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_time_slice.setObjectName("frame_time_slice")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_time_slice)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_time_slice = QtWidgets.QLabel(self.frame_time_slice)
        self.label_time_slice.setObjectName("label_time_slice")
        self.horizontalLayout.addWidget(self.label_time_slice)
        self.lineEdit_time_slice = QtWidgets.QLineEdit(self.frame_time_slice)
        self.lineEdit_time_slice.setObjectName("lineEdit_time_slice")
        self.horizontalLayout.addWidget(self.lineEdit_time_slice)
        self.gridLayout.addWidget(self.frame_time_slice, 5, 2, 1, 1)
        self.label_service = QtWidgets.QLabel(self.frame)
        self.label_service.setObjectName("label_service")
        self.gridLayout.addWidget(self.label_service, 4, 0, 1, 1)
        self.lineEdit_arrive = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_arrive.setObjectName("lineEdit_arrive")
        self.gridLayout.addWidget(self.lineEdit_arrive, 1, 1, 1, 1)
        self.label_arrive = QtWidgets.QLabel(self.frame)
        self.label_arrive.setObjectName("label_arrive")
        self.gridLayout.addWidget(self.label_arrive, 1, 0, 1, 1)
        self.label_method = QtWidgets.QLabel(self.frame)
        self.label_method.setObjectName("label_method")
        self.gridLayout.addWidget(self.label_method, 5, 0, 1, 1)
        self.lineEdit_service = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_service.setObjectName("lineEdit_service")
        self.gridLayout.addWidget(self.lineEdit_service, 4, 1, 1, 1)
        self.frame_random = QtWidgets.QFrame(self.frame)
        self.frame_random.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_random.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_random.setObjectName("frame_random")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_random)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_random = QtWidgets.QLabel(self.frame_random)
        self.label_random.setObjectName("label_random")
        self.horizontalLayout_2.addWidget(self.label_random)
        self.lineEdit_random = QtWidgets.QLineEdit(self.frame_random)
        self.lineEdit_random.setObjectName("lineEdit_random")
        self.horizontalLayout_2.addWidget(self.lineEdit_random)
        self.gridLayout.addWidget(self.frame_random, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "进程调度"))
        self.pushButton_schedule.setText(_translate("MainWindow", "开始调度"))
        self.pushButton_random.setText(_translate("MainWindow", "随机生成"))
        self.comboBox_method.setItemText(0, _translate("MainWindow", "FCFS 先来先服务"))
        self.comboBox_method.setItemText(1, _translate("MainWindow", "RR 轮转算法"))
        self.comboBox_method.setItemText(2, _translate("MainWindow", "HRN 高响应比优先"))
        self.comboBox_method.setItemText(3, _translate("MainWindow", "SJF 短作业优先"))
        self.label_time_slice.setText(_translate("MainWindow", "时间片长度"))
        self.label_service.setText(_translate("MainWindow", "服务时间序列"))
        self.label_arrive.setText(_translate("MainWindow", "到达时间序列"))
        self.label_method.setText(_translate("MainWindow", "选择调度算法"))
        self.label_random.setText(_translate("MainWindow", "随机生成进程个数"))
